# Generated by Django 4.1.7 on 2023-03-27 00:29

from django.db import migrations, models
from django.contrib.auth.models import User
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(blank=True, default=users.models.Classroom.create_new_class_code, editable=False, max_length=6, null=True),
        ),
    ]
