# Generated by Django 4.1.7 on 2023-03-27 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=6, null=True),
        ),
    ]
