# Generated by Django 4.1.7 on 2023-03-27 00:31

from django.db import migrations
from django.contrib.auth.models import User

def create_new_class_code():
        not_unique = True
        while not_unique:
            unique_ref = random.randint(1000000000, 9999999999)
            if not Transaction.objects.filter(Referrence_Number=unique_ref):
                not_unique = False
        return str(unique_ref)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_classroom_class_code'),
    ]

    operations = [
        migrations.RunPython(create_new_class_code)
    ]
