# Generated by Django 4.1.7 on 2023-03-27 00:31

from django.db import migrations, models
from django.contrib.auth.models import User
from users.models import Classroom
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230326_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(blank=True, default=Classroom.create_new_class_code, editable=False, max_length=6, unique=True),
        )
    ]
