# Generated by Django 4.1.7 on 2023-03-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230327_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_class_code',
            field=models.TextField(default='EMPTY'),
        ),
    ]
