# Generated by Django 4.1.7 on 2023-03-28 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_student_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=6, unique=True),
        ),
    ]
