# Generated by Django 4.1.7 on 2023-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_classroom_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_classroom',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_class_code',
            field=models.TextField(null=True),
        ),
    ]
