# Generated by Django 4.1.7 on 2023-03-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_student_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_classroom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_class_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
