# Generated by Django 4.1.7 on 2023-03-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_student_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_classroom',
        ),
        migrations.AddField(
            model_name='profile',
            name='student_classroom',
            field=models.ManyToManyField(to='users.classroom'),
        ),
    ]
