# Generated by Django 4.1 on 2023-04-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Grasp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Mood',
            field=models.IntegerField(default=0),
        ),
    ]
