# Generated by Django 4.1 on 2023-04-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_grasp_profile_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Grasp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Mood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='student_classroom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_class_code',
        ),
    ]
