# Generated by Django 4.1 on 2023-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_profile_grasp_remove_profile_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isteacher',
            field=models.BooleanField(default=False),
        ),
    ]
