# Generated by Django 4.1 on 2023-04-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_isteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isteacher',
        ),
    ]
