# Generated by Django 4.1 on 2023-05-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_profile_is_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("a", "light"),
                    ("b", "dark"),
                    ("c", "cupcake"),
                    ("d", "bumblebee"),
                    ("e", "emerald"),
                    ("f", "corporate"),
                    ("g", "synthwave"),
                    ("h", "valentine"),
                    ("i", "halloween"),
                    ("j", "forest"),
                    ("k", "luxury"),
                    ("l", "night"),
                ],
                default="h",
                max_length=1,
            ),
        ),
    ]
