# Generated by Django 4.1 on 2023-05-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_profile_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("cupcake", "Cupcake🧁"),
                    ("bumblebee", "Bumblebee🐝"),
                    ("emerald", "Emerald🍀"),
                    ("mytheme", "Robel😎"),
                    ("corporate", "Corporate📊"),
                    ("synthwave", "Synthwave🔉"),
                    ("valentine", "Valentine❤️"),
                    ("halloween", "Halloween🎃"),
                    ("forest", "Forest🌲"),
                    ("luxury", "Luxury💰"),
                    ("night", "Night🌚"),
                ],
                default="default",
                max_length=15,
            ),
        ),
    ]
