# Generated by Django 4.1 on 2023-05-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_alter_profile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="banner",
            field=models.ImageField(
                default="sample_banner.png", upload_to="class_banners"
            ),
        ),
    ]
