# Generated by Django 4.1 on 2023-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_classroom_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="logo",
            field=models.ImageField(
                default="default_class_logo.png", upload_to="class_logos"
            ),
        ),
    ]
