# Generated by Django 4.1 on 2023-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_classroom_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="banner",
            field=models.ImageField(
                default="class_banners/sample_banner.png", upload_to="class_banners"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="logo",
            field=models.ImageField(
                default="class_logos/default_class_logo.png", upload_to="class_logos"
            ),
        ),
    ]
