# Generated by Django 4.1.7 on 2023-04-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0002_sliderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='SliderData',
        ),
    ]
