# Generated by Django 4.1 on 2023-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0005_alter_surveyquestion_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='grasp_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='mood_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
