# Generated by Django 4.1 on 2023-04-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0007_remove_student_name_remove_student_rank_student_gpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='emoji_1',
            field=models.ImageField(default='angry.png', upload_to='chartjs/static/emojis'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='emoji_2',
            field=models.ImageField(default='conflict.png', upload_to='chartjs/static/emojis'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='emoji_3',
            field=models.ImageField(default='meh.png', upload_to='chartjs/static/emojis'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='emoji_4',
            field=models.ImageField(default='good.png', upload_to='chartjs/static/emojis'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='emoji_5',
            field=models.ImageField(default='happy.png', upload_to='chartjs/static/emojis'),
        ),
    ]
