# Generated by Django 4.1 on 2023-04-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_profile_grasp_remove_profile_mood_and_more'),
        ('chartjs', '0009_remove_surveyquestion_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Grasp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='Mood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_classroom',
            field=models.ManyToManyField(blank=True, to='users.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_class_code',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
