# Generated by Django 4.1 on 2023-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0010_student_grasp_student_mood_student_student_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='question',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
