# Generated by Django 4.1.7 on 2023-03-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='class_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
